### PR TITLE
(docs): Update for Docs

### PR DESCRIPTION
**Pull request by maisans-maid**
Please check if this update can be merged without breaking the site. Thank you

### CODE REVIEW

**Comment by maisans-maid** [comment]
most of my syntax errors were the one with mismatched tags, i thought we could just do like </br> alone, but seems impossible, check my latest PR instead. Also, check again the for errors. I crossed-check my file before i commit so im pretty sure most of the syntax errors were fixed.

**Comment by maisans-maid** [comment]
F, i accidentally merged them :(

**Comment by BearTS** [comment]
> most of my syntax errors were the one with mismatched tags, i thought we could just do like \</br> alone, but seems impossible, check my latest PR instead. Also, check again the for errors. I crossed-check my file before i commit so im pretty sure most of the syntax errors were fixed.
> 

u can use br alone
you need to do <br/> instead of <br>

**Comment by maisans-maid** [comment]
Yeah, I noticed.

**Pull request merged**
